### ISSUE TITLE
Support COSE/CBOR

### ISSUE THREAD

**Issue by sajayantony** [Azure/notation-azure-kv#11]
Tracking issue to support notation-azure-kv extension to support COSE/CBOR - https://github.com/notaryproject/notaryproject/pull/139

This depends on - https://github.com/veraison/go-cose/issues/9

**Comment by SteveLasker** [comment]
The veraison/go-cose branch is now ready for consumption:
- [ ] Complete remote signing support: [veraison/go-cose #9](https://github.com/veraison/go-cose/issues/9)
- [ ] Notary Spec support of COSE [#48](https://github.com/notaryproject/notaryproject/pull/148)
- [ ] notation support for COSE [#163](https://github.com/notaryproject/notation/issues/163)
- [ ] Update notation-azure-kv to support COSE signing with Azure Key Vault
 
https://github.com/notaryproject/notation/issues/162

**Comment by shizhMSFT** [comment]
Closing since the COSE support is added in notation-core-go alpha.4.
